// <auto-generated />
using DataLayer.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations.DynamicDb
{
    [DbContext(typeof(DynamicDbContext))]
    [Migration("20250128205513_شیی قثمشفهخد سثثی")]
    partial class شییقثمشفهخدسثثی
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.FormBuilder.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlFormBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Form");
                });

            modelBuilder.Entity("Entities.Models.MainEngine.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RelationLists",
                            PreviewName = "RelationLists",
                            TableName = "RelationLists"
                        });
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.EntityProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsRequiredErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToolType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("EntityProperty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RelationId",
                            EntityId = 1,
                            PreviewName = "RelationId",
                            PropertyName = "RelationId",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Element2",
                            EntityId = 1,
                            PreviewName = "Element2",
                            PropertyName = "Element2",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Element1",
                            EntityId = 1,
                            PreviewName = "Element1",
                            PropertyName = "Element1",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "WorkflowUserId",
                            EntityId = 1,
                            PreviewName = "WorkflowUserId",
                            PropertyName = "WorkflowUserId",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.Entity_EntityRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Entity_EntityRelation");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.RelationList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Element1")
                        .HasColumnType("int");

                    b.Property<int>("Element2")
                        .HasColumnType("int");

                    b.Property<int>("RelationId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelationId");

                    b.ToTable("RelationLists");
                });

            modelBuilder.Entity("EntityForm", b =>
                {
                    b.Property<int>("EntitiesId")
                        .HasColumnType("int");

                    b.Property<int>("FormsId")
                        .HasColumnType("int");

                    b.HasKey("EntitiesId", "FormsId");

                    b.HasIndex("FormsId");

                    b.ToTable("EntityForm");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.EntityProperty", b =>
                {
                    b.HasOne("Entities.Models.TableBuilder.Entity", "Entity")
                        .WithMany("Properties")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.Entity_EntityRelation", b =>
                {
                    b.HasOne("Entities.Models.TableBuilder.Entity", null)
                        .WithMany("entity_EntityRelation")
                        .HasForeignKey("EntityId");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.RelationList", b =>
                {
                    b.HasOne("Entities.Models.TableBuilder.Entity_EntityRelation", "Relation")
                        .WithMany("RelationLists")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("EntityForm", b =>
                {
                    b.HasOne("Entities.Models.TableBuilder.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.FormBuilder.Form", null)
                        .WithMany()
                        .HasForeignKey("FormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.Entity", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("entity_EntityRelation");
                });

            modelBuilder.Entity("Entities.Models.TableBuilder.Entity_EntityRelation", b =>
                {
                    b.Navigation("RelationLists");
                });
#pragma warning restore 612, 618
        }
    }
}
